### ISSUE TITLE
Create introduction page

### ISSUE THREAD

**Issue by Jesse-Kramer** [fdnd-agency/tumi-mundo#15]
## What does this mean

Implement the introduction page based on the design below.

> Before you assign this issue or start working on it, read the "Important" section below for critical details.

## Figma design
![image](https://github.com/user-attachments/assets/e7f7f8ee-32e9-4760-a2a3-91da80d8d7fe)

For more detailed information, access the full design on Figma: [View Figma Design](https://www.figma.com/design/RDlD4etdXBvcOW9AAqueBz/TuMiMundo_FDND_Prototype?node-id=0-1&node-type=canvas&t=3fsxErKvILrEWsyV-0) 

## Important
-

**Comment by lemuelmgsn** [comment]
De basis van de pagina is klaar!

What needs to be done: 

De carousel maken met de indicators

Results:

![Image](https://github.com/user-attachments/assets/2fa8c119-5bd6-42d2-a123-19437d7c8257)

![Image](https://github.com/user-attachments/assets/1bc3e5e6-2deb-4795-8d1e-9abdd0a62d24)

![Image](https://github.com/user-attachments/assets/92e3954c-2ca7-4363-a8b5-ac7b72d197c8)
