### ISSUE TITLE
Create register page

### ISSUE THREAD

**Issue by Jesse-Kramer** [fdnd-agency/tumi-mundo#16]
## What does this mean

Implement the register page based on the design below. This task does not include adding dynamic data — that will be done later.

> Before you assign this issue or start working on it, read the "Important" section below for critical details.

## Figma design
![image](https://github.com/user-attachments/assets/f587b1ba-ed6e-43d9-a297-f3344f8506b8)

For more detailed information, access the full design on Figma: [View Figma Design](https://www.figma.com/design/RDlD4etdXBvcOW9AAqueBz/TuMiMundo_FDND_Prototype?node-id=0-1&node-type=canvas&t=3fsxErKvILrEWsyV-0) 

## Important
* This task does not include adding dynamic data — that will be done later.

**Comment by lemuelmgsn** [comment]
De basis van de pagina is klaar!

What needs to be done:

- De popup moet toegevoegd worden
- Een svg voor de "back" button

![Image](https://github.com/user-attachments/assets/2e426235-5cd4-4bcc-883b-4bd6b67eeeda)
