### ISSUE TITLE
Sprint review 10 okt

### ISSUE THREAD

**Issue by Akikosophia** [fdnd-agency/tumi-mundo#47]

**Comment by Akikosophia** [comment]
Sprint review:Tumi Mundo

Suggesties en vragen voor de opdrachtgever
- Play button op de img
- Iconen veranderen in de stories
- Tekst algemeen moet iets groter 

Akiko
- All stories pages
- Aanpassing carousel tekst iets groter + scroll
- Mp3 geluid afspelen
- Like playlist kunnen opslaan in favorieten
- Achtergrond kleuren kunnen aangepast worden (voor een betere kleurencontrast)

Feedback van de opdrachtgever
- Iconen kunnen veranderd worden (bijvoorbeeld een like button)
- Ze willen in de stories ook een optie kunnen hebben met welke stem (man of vrouw)

**Comment by lemuelmgsn** [comment]
# Sprintreview: Tumi Mundo

### Suggesties en vragen voor opdrachtgever:

- Andere kleurengebruik? kleurencontrast niet voldoende.
- Per onboarding slide een andere muis/rat foto?
- Lettertype is te klein

### Antwoorden van de opdrachtgever:

- Kleuren worden later aangeleverd, ze hebben eerder een kleurentest gedaan en zullen die resultaten naar ons sturen.
- De muis is nu nog 1 image omdat ze hebben besloten om later aan de verschillende muizen/animaties te werken. en er daarom maar 1 afbeelding in het Figma bestand zit.
- Lettertype mag uiteraard groter

**Comment by Jesse-Kramer** [comment]
# Sprintreview: Tumi Mundo
## Jesse
### Suggesties en vragen voor opdrachtgever:
Q: We hebben feedback gekregen op het design, wat vinden jullie van deze punten? (#32 #33 #34 #35 )
A: Font-sizes klopt inderdaad, we hebben hier een verbeterde versie van en die sturen jullie door. Ook over de kleuren klopt het, dit stuur ik ook door.

Q: Hebben jullie al verhaaltjes en geluidsfragmenten die wij kunnen gebruiken.
A: Ja zeker, die zullen we doorsturen. 

### Feedback van de opdrachtgever:
Heel mooi dat het menu en de home pagina werkt! Als de data helemaal werkend is probeer dan te kijken of je de progress bar daarmee kan verbinden.
