### ISSUE TITLE
Create the database connection and implement data inside the database 

### ISSUE THREAD

**Issue by lemuelmgsn** [fdnd-agency/tumi-mundo#9]
## What does this mean

Implement the data based on the datamodel below.

> Before you assign this issue or start working on it, read the "Important" section below for critical details.

## Datamodel
![Image](https://github.com/user-attachments/assets/10ad7aba-3812-4884-bc63-c9052f3c2ffa)

For more detailed information, access the full design on Figma: [View Figma Design](https://www.figma.com/design/RDlD4etdXBvcOW9AAqueBz/TuMiMundo_FDND_Prototype?node-id=0-1&node-type=canvas&t=3fsxErKvILrEWsyV-0)

**Comment by Jesse-Kramer** [comment]
Pull request staat open!
